# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: nestr-key-agent

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: keyagent
    main: ./services/generic/main.go
    binary: keyagent
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: keyagent-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - agent.protobuf
      - install.sh
      - install.ps1

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: HORNET-Storage
    name: nestr-key-agent
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

# Linux packages (DEB/RPM)
nfpms:
  - id: keyagent
    package_name: nestr-key-agent
    vendor: HORNET-Storage
    homepage: https://github.com/HORNET-Storage/nestr-key-agent
    maintainer: HORNET-Storage <dev@hornet-storage.io>
    description: |
      Secure key management agent for GitNestr.
      The Nestr Key Agent runs as a background service and provides secure
      cryptographic key management with AES-256 GCM encryption and time-limited caching.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./scripts/keyagent.service
        dst: /lib/systemd/system/keyagent.service
      - src: ./install.sh
        dst: /usr/share/nestr-key-agent/install.sh
        file_info:
          mode: 0755
    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
      postremove: "scripts/postremove.sh"

# Homebrew tap for macOS (commented out until GH_PAT secret is configured)
# See GITHUB_SECRETS_SETUP.md for instructions
# brews:
#   - repository:
#       owner: HORNET-Storage
#       name: homebrew-tap
#       token: "{{ .Env.GH_PAT }}"
#     homepage: https://github.com/HORNET-Storage/nestr-key-agent
#     description: Secure key management agent for GitNestr
#     license: MIT
#     install: |
#       bin.install "keyagent"
#     test: |
#       system "#{bin}/keyagent", "--version"
#     service: |
#       run [opt_bin/"keyagent"]
#       keep_alive true
#       log_path var/"log/keyagent.log"
#       error_log_path var/"log/keyagent.log"
