// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: agent.protobuf

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyName    string `protobuf:"bytes,1,opt,name=keyName,proto3" json:"keyName,omitempty"`
	PrivateKey string `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	Passphrase string `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
}

func (x *StoreKeyRequest) Reset() {
	*x = StoreKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_protobuf_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKeyRequest) ProtoMessage() {}

func (x *StoreKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_protobuf_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKeyRequest.ProtoReflect.Descriptor instead.
func (*StoreKeyRequest) Descriptor() ([]byte, []int) {
	return file_agent_protobuf_rawDescGZIP(), []int{0}
}

func (x *StoreKeyRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *StoreKeyRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *StoreKeyRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type StoreKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StoreKeyResponse) Reset() {
	*x = StoreKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_protobuf_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKeyResponse) ProtoMessage() {}

func (x *StoreKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_protobuf_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKeyResponse.ProtoReflect.Descriptor instead.
func (*StoreKeyResponse) Descriptor() ([]byte, []int) {
	return file_agent_protobuf_rawDescGZIP(), []int{1}
}

func (x *StoreKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RetrieveKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyName    string `protobuf:"bytes,1,opt,name=keyName,proto3" json:"keyName,omitempty"`
	Passphrase string `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
}

func (x *RetrieveKeyRequest) Reset() {
	*x = RetrieveKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_protobuf_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveKeyRequest) ProtoMessage() {}

func (x *RetrieveKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_protobuf_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveKeyRequest.ProtoReflect.Descriptor instead.
func (*RetrieveKeyRequest) Descriptor() ([]byte, []int) {
	return file_agent_protobuf_rawDescGZIP(), []int{2}
}

func (x *RetrieveKeyRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *RetrieveKeyRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type RetrieveKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey string `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
}

func (x *RetrieveKeyResponse) Reset() {
	*x = RetrieveKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_protobuf_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveKeyResponse) ProtoMessage() {}

func (x *RetrieveKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_protobuf_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveKeyResponse.ProtoReflect.Descriptor instead.
func (*RetrieveKeyResponse) Descriptor() ([]byte, []int) {
	return file_agent_protobuf_rawDescGZIP(), []int{3}
}

func (x *RetrieveKeyResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

var File_agent_protobuf protoreflect.FileDescriptor

var file_agent_protobuf_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x12, 0x0d, 0x6e, 0x65, 0x73, 0x74, 0x72, 0x6b, 0x65, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22,
	0x6b, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x61, 0x73, 0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x61, 0x73, 0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x10,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4e, 0x0a, 0x12, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61,
	0x73, 0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x61, 0x73, 0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x22, 0x35, 0x0a, 0x13, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x32, 0xb1, 0x01, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x4d,
	0x0a, 0x08, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x2e, 0x6e, 0x65, 0x73,
	0x74, 0x72, 0x6b, 0x65, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x65, 0x73,
	0x74, 0x72, 0x6b, 0x65, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a,
	0x0b, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x2e, 0x6e,
	0x65, 0x73, 0x74, 0x72, 0x6b, 0x65, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x72, 0x6b, 0x65, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x6e, 0x65, 0x73, 0x74, 0x72, 0x2d, 0x6b,
	0x65, 0x79, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_protobuf_rawDescOnce sync.Once
	file_agent_protobuf_rawDescData = file_agent_protobuf_rawDesc
)

func file_agent_protobuf_rawDescGZIP() []byte {
	file_agent_protobuf_rawDescOnce.Do(func() {
		file_agent_protobuf_rawDescData = protoimpl.X.CompressGZIP(file_agent_protobuf_rawDescData)
	})
	return file_agent_protobuf_rawDescData
}

var file_agent_protobuf_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_protobuf_goTypes = []interface{}{
	(*StoreKeyRequest)(nil),     // 0: nestrkeyagent.StoreKeyRequest
	(*StoreKeyResponse)(nil),    // 1: nestrkeyagent.StoreKeyResponse
	(*RetrieveKeyRequest)(nil),  // 2: nestrkeyagent.RetrieveKeyRequest
	(*RetrieveKeyResponse)(nil), // 3: nestrkeyagent.RetrieveKeyResponse
}
var file_agent_protobuf_depIdxs = []int32{
	0, // 0: nestrkeyagent.KeyAgent.StoreKey:input_type -> nestrkeyagent.StoreKeyRequest
	2, // 1: nestrkeyagent.KeyAgent.RetrieveKey:input_type -> nestrkeyagent.RetrieveKeyRequest
	1, // 2: nestrkeyagent.KeyAgent.StoreKey:output_type -> nestrkeyagent.StoreKeyResponse
	3, // 3: nestrkeyagent.KeyAgent.RetrieveKey:output_type -> nestrkeyagent.RetrieveKeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_protobuf_init() }
func file_agent_protobuf_init() {
	if File_agent_protobuf != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_protobuf_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_protobuf_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_protobuf_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_protobuf_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_protobuf_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_protobuf_goTypes,
		DependencyIndexes: file_agent_protobuf_depIdxs,
		MessageInfos:      file_agent_protobuf_msgTypes,
	}.Build()
	File_agent_protobuf = out.File
	file_agent_protobuf_rawDesc = nil
	file_agent_protobuf_goTypes = nil
	file_agent_protobuf_depIdxs = nil
}
